"""Generate a compact, link-first context pack for a job (no giant file dumps)."""
from __future__ import annotations

from pathlib import Path
from typing import List

from .job_loader import repo_root
from .schemas import GateEvaluation, JobSpec, StateResult


def _exists_links(root: Path, candidates: List[str]) -> List[str]:
    out = []
    for rel in candidates:
        if (root / rel).exists():
            out.append(f"- `{rel}`")
    return out


def build(job: JobSpec, state: StateResult, gates: GateEvaluation) -> Path:
    root = repo_root()
    lines: List[str] = []
    A = lines.append
    A(f"# Context Pack — {job.job_id}")
    A("")
    A("> Auto-generated by MQAI. Link-first: summarizes + references paths; does not dump files.")
    A("")
    A("## Objective")
    A(job.objective or job.title)
    A("")
    A("## Current state")
    A(f"- state: **{state.current_state}**")
    A(f"- risk tier: **{gates.tier}**")
    A(f"- location: {job.location}  ·  status: {job.status}")
    A(f"- evidence: {', '.join(state.evidence) or 'none'}")
    A("")
    A("## Next allowed action")
    A(f"- {gates.next_action}")
    if gates.next_gate:
        A(f"- next gate: `{gates.next_gate}`  ·  human approval required: {gates.human_required}")
    A("")
    A("## Gates")
    for g in gates.gates:
        A(f"- `{g.name}`: {g.status}"
          + (f" (human)" if g.human_required else "")
          + (f" — {g.detail}" if g.detail else ""))
    A("")
    A("## Hard stops (global)")
    for hs in [
        "no push to remote", "no history rewrite", "no secret-content inspection",
        "no product-repo writes unless the job authorizes it", "no `git add -A` in product repos",
        "no modifying formulas / live execution / schema / MQCHAIN registry outside an approved job",
    ]:
        A(f"- {hs}")
    A("")
    A("## Allowed writes")
    for w in job.allowed_writes or ["(none declared)"]:
        A(f"- `{w}`")
    A("")
    A("## Forbidden writes")
    for w in job.forbidden_writes or ["(none declared)"]:
        A(f"- `{w}`")
    A("")
    A("## Blocked actions (current)")
    for b in gates.blocked_actions or ["(none)"]:
        A(f"- {b}")
    A("")
    A("## Relevant governance (if present)")
    A("### repo_control")
    A("\n".join(_exists_links(root, [f"repo_control/{r}/rules.md" for r in [
        "mqnode_test2", "mqnode_cloud"]] + [
        "repo_control/mqengine/research_protocol.md",
        "repo_control/mamakquantchainintel/label_governance.md"])) or "- (none)")
    A("### skills")
    A("\n".join(_exists_links(root, [
        "skills/code_reviewer.md", "skills/repo_mapper.md",
    ])) or "- (none)")
    A("### memory")
    A("\n".join(_exists_links(root, ["memory/decisions.md", "memory/lessons_learned.md"])) or "- (none)")
    A("")
    A("## Validation requirements")
    A("- Run local eval gates via `mqai eval` (risk_tier, write_scope, secret_scan, touched_path, git_status).")
    A("- HIGH/CRITICAL also require executed-diff review + GPT synthesis + Cray final approval before commit.")
    A("")
    A("## Compact output format expected from agents")
    A("- status · next action · gates passed/pending · changed files · product repos touched · blockers · required human decision.")
    A("")
    s = state.signals
    A("## Handoff / continuity")
    A(f"- handoff_ready: {'true' if s.get('handoff_ready') else 'false'}")
    A(f"- resume path: {s.get('resume_prompt_path') or '(none — run `mqai handoff` / `mqai resume`)'}")
    A(f"- recommended next agent: {s.get('recommended_next_agent') or '(none)'}")
    A("- continuation policy: resume from these files, NOT from chat history. MQAI owns memory/state/"
      "gates/handoff; agents are temporary compute; Cray is final risk owner.")
    A("- **agents do not share memory** — a resuming agent must read the job + handoff files.")
    A("")

    job.output_dir.mkdir(parents=True, exist_ok=True)
    dest = job.output_dir / "context_pack.md"
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest
